import type { RawCatalogRow } from "./types";

export function generateSampleCatalog(): RawCatalogRow[] {
  return [
    {
      sku: "KIT-1001",
      title: "Premium Stainless Steel Mixing Bowls Set of 5 with Lids — Nesting Design for Easy Storage",
      bullets: "Set of 5 sizes (1qt, 1.5qt, 3qt, 4qt, 5qt)|Airtight lids included|Dishwasher safe stainless steel|Non-slip base|Measurement markings inside",
      description: "Professional grade mixing bowls perfect for everyday cooking and baking. The nesting design saves cabinet space while the airtight lids keep food fresh.",
      category: "Kitchen",
      brand: "Northfield",
      image_count: "7",
      price: "34.99",
    },
    {
      sku: "EL-2001",
      title: "Wireless Bluetooth Earbuds with Active Noise Cancellation — 30 Hour Battery Life",
      bullets: "Active noise cancellation|30 hour total battery life|IPX5 water resistant|Bluetooth 5.2|USB-C charging case",
      description: "Experience crystal clear audio with our premium wireless earbuds. Advanced ANC technology blocks out background noise for immersive listening.",
      category: "Electronics",
      brand: "Vantix",
      image_count: "6",
      price: "59.99",
    },
    {
      sku: "HB-3001",
      title: "Organic Lavender Essential Oil 100ml — Pure Therapeutic Grade for Aromatherapy and Relaxation",
      bullets: "100% pure organic lavender|Therapeutic grade certified|Works with all diffusers|Calming and relaxing scent|30 day satisfaction guarantee",
      description: "Our premium lavender essential oil is steam distilled from organically grown lavender flowers. Perfect for diffusers, massage, and skincare.",
      category: "Health & Beauty",
      brand: "Verdette",
      image_count: "5",
      price: "14.99",
    },
    {
      sku: "KIT-1002",
      title: "Silicone Spatula Set of 4 Heat Resistant Kitchen Utensils for Cooking and Baking",
      bullets: "Heat resistant to 450°F|BPA free silicone|Dishwasher safe|Ergonomic handle|4 piece set",
      description: "Versatile silicone spatulas suitable for all cookware types including non-stick pans.",
      category: "Kitchen",
      brand: "Cedar & Co",
      image_count: "0",
      price: "12.99",
    },
    {
      sku: "SP-4001",
      title: "Resistance Bands Set for Home Workout — 5 Levels of Tension for Strength Training",
      bullets: "5 resistance levels|Natural latex material|Includes carry bag|Suitable for all fitness levels|Door anchor included",
      description: "Build strength and flexibility at home with our professional resistance bands set.",
      category: "Sports",
      brand: "Ridgeway",
      image_count: "0",
      price: "24.99",
    },
    {
      sku: "OF-6001",
      title: "Stapler",
      bullets: "Staples paper|Black color|Standard size",
      description: "A stapler for office use.",
      category: "Office",
      brand: "Rowan Supply",
      image_count: "2",
      price: "8.99",
    },
    {
      sku: "TY-5001",
      title: "Toy Car Red",
      bullets: "Red color|Plastic",
      description: "Toy car for kids.",
      category: "Toys",
      brand: "Kindle & Pip",
      image_count: "1",
      price: "9.99",
    },
    {
      sku: "HB-3002",
      title: "Vitamin C Serum 20% Concentration Anti-Aging Face Serum with Hyaluronic Acid",
      bullets: "",
      description: "Powerful vitamin C serum that brightens skin and reduces the appearance of fine lines.",
      category: "Health & Beauty",
      brand: "Lumen",
      image_count: "4",
      price: "22.99",
    },
    {
      sku: "KIT-1003",
      title: "Premium Stainless Steel Mixing Bowls Set of 5 with Lids — Nesting Design for Easy Storage",
      bullets: "Set of 5 sizes|Airtight lids|Dishwasher safe|Non-slip base|Measurement markings",
      description: "Professional grade mixing bowls perfect for everyday cooking and baking.",
      category: "Kitchen",
      brand: "Northfield",
      image_count: "7",
      price: "34.99",
    },
    {
      sku: "EL-2002",
      title: "Wireless Bluetooth Earbuds Noise Cancelling 30 Hour Battery",
      bullets: "Noise cancellation|30 hour battery|Water resistant|Bluetooth 5.2|USB-C charging",
      description: "Experience crystal clear audio with our premium wireless earbuds.",
      category: "Electronics",
      brand: "Vantix",
      image_count: "5",
      price: "57.99",
    },
    {
      sku: "OF-6002",
      title: "Mechanical Keyboard Wireless Compact 75% Layout with RGB Backlight for Mac and Windows",
      bullets: "75% compact layout|Wireless 2.4GHz and Bluetooth|RGB per-key backlighting|Compatible with Mac and Windows|Hot-swappable switches",
      description: "Upgrade your desk setup with our premium mechanical keyboard featuring a space-saving 75% layout.",
      category: "Office",
      brand: "Rowan Supply",
      image_count: "8",
      price: "89.99",
    },
    {
      sku: "TY-5002",
      title: "Building Blocks Set 500 Pieces Classic Construction Toy for Kids Age 4 and Up",
      bullets: "500 pieces included|Compatible with major brands|Bright colors|Safe non-toxic plastic|Storage box included",
      description: "",
      category: "Toys",
      brand: "Kindle & Pip",
      image_count: "4",
      price: "29.99",
    },
  ];
}

export function sampleCatalogHeaders(): string[] {
  return [
    "sku",
    "title",
    "bullets",
    "description",
    "category",
    "brand",
    "image_count",
    "price",
  ];
}